Update ecc_analysis.py, fix UnboundLocalError
UnboundLocalError: cannot access local variable 'point_exponent' where it is not associated with a value. The name of the function is used as a variable in the function itself, which leads to an UnboundLocalError. This commit fixes this bug.